### ISSUE TITLE
[Suggestion] Scrolling the list with arrows

### ISSUE THREAD

**Issue by arjunmahishi** [Chalarangelo/30-seconds-of-code#272]
On the website, is it possible to scroll the lift side panel list with arrows? Like when you search for the snippet, the list gets filtered. If you could scroll the list with arrows and hit enter to view the snippet, it would be amazing. 
(like how it happens on WhatsApp web)

I am not sure how setting focus on the list items works. If someone can guide me through it, I can work on it.

**Comment by Chalarangelo** [comment]
That would be a nice feature, give it a try and I would be glad to merge a PR with it! 😉

**Comment by arjunmahishi** [comment]
# Example 
![example](https://user-images.githubusercontent.com/11977524/34220538-feeca72c-e5da-11e7-8fac-00c15ebbef0e.gif)

**Comment by skatcat31** [comment]
This is a fairly annoying feature to implement since you need state. A clear design path before implementation would be need otherwise you run the risk of a hard to reason monster. The search would need to be re written to accommodate it. And the search was in such a nice snippet too. Oh well. That's the nature of refactoring for the future.

**Comment by Chalarangelo** [comment]
I like what I see, but we want to avoid code bloating, as the website is getting heavier by the day. This might not be a necessary feature and I'm starting to question if we should implement it right now, based on what @skatcat31 said.

**Comment by arjunmahishi** [comment]
Yes it's too tedious...

**Comment by skatcat31** [comment]
This is exactly what I do at work: Let people know how hard, simple, or about what they want to do
