### ISSUE TITLE
[FEATURE] Array sort function 

### ISSUE THREAD

**Issue by xqdoo00o** [Chalarangelo/30-seconds-of-code#352]
## Description
here is the code.
## Example
By default (without arg 'des'), it's ascending sort.

`let qs = ([x,...s],des)=> isNaN(x) ? [] : [...qs(s.filter(v=>des?v>x:v<=x),des), x, ...qs(s.filter(v=>des?v<=x:v>x),des)];`

**Comment by atomiks** [comment]
Is this to show how quicksort works (aka without `sort()`)? I think it needs to be a bit more readable, like this:

```js
const quickSort = ([x, ...s], desc) =>
  !isNaN(x)
    ? [
        ...quickSort(s.filter(v => (desc ? v > x : v <= x)), desc),
        x,
        ...quickSort(s.filter(v => (desc ? v <= x : v > x)), desc)
      ]
    : [];

```

**Comment by skatcat31** [comment]
@atomiks you should structure ternaries and control statements in order of length, shortest first. So in this case you'd want to do the following to enhance readabilty:
```js
const quickSort = ([x, ...s], d) =>
  isNaN(x) ?
    [] :
    [
      ...quickSort(s.filter(v => (desc ? v > x : v <= x), desc),
      x,
      ...quickSort(s.filter(v =>(!desc ? v > x : v <= x), desc)
    ]
```
Now I don't have to read further to see what I should respond with if it `isNaN`. I can easily glance and notice.

Also as a note on the secondary I decided to negate the desc so that we can keep the ternary the same, just a different conditional, making it easier to notice if I typed a mistake( ignore the fact that I'm cheating on the spacing of the parens, it makes it line up real nice and pretty )

**Comment by atomiks** [comment]
tbh yeah I usually prefer a non-negated expression, but usually put the shorter one (the "default") at the end. In the above case yours is better I agree

**Comment by skatcat31** [comment]
You really should go shorter to longer for sake of developer traversal, regardless of which is the default. After all which server responding middlware is easier to read( purposefully stylized this way for length example, and sadly I've seen this style of coding in production -.-;;):
```js
if (!req.user.authorized) return res.sendStatus(401)
return req
  .app
  .locals
  .db
  .users
  .loadProfile(
    req
    .user
    .id
  )
  .then(
    res.render.bind(
      res,
      'userProfile'
    )
  )
```
```js
if (req.user.authorized) return req
  .app
  .locals
  .db
  .users
  .loadProfile(
    req
    .user
    .id
  )
  .then(
    res.render.bind(
      res,
      'userProfile'
    )
  )
return res.sendStatus(401);
```
The longer the code snippet, the more reading you need to do before seeing the next block. Now to be fair this isn't exactly the best example, but it gets the idea across that seeing shorter cases is nice because it means you can much more quickly traverse your code. Collapsing to a kerning level doesn't help when you don't know what you're looking for after all.

Granted all of this is arbitrary.

**Comment by xqdoo00o** [comment]
I Agree too.

**Comment by Chalarangelo** [comment]
I haven't had the time to check this out the past few days, but it seems worthwhile. You should PR it!

**Comment by skatcat31** [comment]
@xqdoo00o since you submitted the code and saw a couple of coding examples, would you want to submit the PR yourself?

**Comment by xqdoo00o** [comment]
@skatcat31 It's done. see [#quicksort](https://github.com/Chalarangelo/30-seconds-of-code#quicksort)
