### ISSUE TITLE
[FEATURE] Allow snippets to be imported with es6 modules/npm

### ISSUE THREAD

**Issue by achung89** [Chalarangelo/30-seconds-of-code#375]
### Description 
Love your work, would be nice if we could import these directly into our applications.

**Comment by Chalarangelo** [comment]
This issue has been discussed in length over and over again. We have no intention of creating a package out of the snippets, as they are in no way production-ready. However, we are interested in creating a side-project that will update regularly with this kind of scope, so that people can import the snippets they need. This is probably quite a long time away, but expect some kind of move in that direction eventually.
