### ISSUE TITLE
[BUG] "Show Examples" not working in Firefox

### ISSUE THREAD

**Issue by fplgusmao** [Chalarangelo/30-seconds-of-code#471]
### Expected Behavior

When clicking "Show Examples" a window should expand with a code snippet.

### Current Snippet Behavior

When clicking "Show Examples" (in Firefox v58.0b13 (64-bit) for Mac) a window expands but its content is blank (see image)
![show example firefox bug](https://user-images.githubusercontent.com/8159837/34517636-b6677132-f073-11e7-91d5-7a91ab789637.png)

However, when scrolling past the section, and then scrolling to it again, the code is rendered

**Comment by Chalarangelo** [comment]
We are aware of some rendering problems on the website, thanks for reporting this! I cannot reproduce this at the current time, but there will be some fixes applied to the website's CSS soon (possibly today or tomorrow), so hold tight until we deploy them (I'll add a comment here, so that you can test and inform me if something is still broken).

**Comment by Chalarangelo** [comment]
**Update:** The website has been updated since last night, let us know if the issue persists.

**Comment by fplgusmao** [comment]
Working!
