### ISSUE TITLE
A few fixes and additions

### ISSUE THREAD

**Issue by atomiks** [Chalarangelo/30-seconds-of-code#50]
I can't create a pull atm, but I went through the README.

### Deep flatten array

```javascript
const deepFlatten = arr =>
  arr.reduce( (a, v) => a.concat( Array.isArray(v) ? flatten(v) : v ), []);
```

`flatten` should be `deepFlatten`

### Last of list

```javascript
const last = arr => arr[arr.length - 1];
```
Why not use this instead of `.slice(-1)[0]`?

### Random integer in range
```javascript
const randomIntegerInRange = (min, max) => 
  Math.floor(Math.random() * (max - min + 1)) + min;
```

### Median of an array of numbers

```javascript
const median = numbers => {
  const midpoint = Math.floor(numbers.length / 2)
  const sorted = numbers.sort((a, b) => a - b)

  return numbers.length % 2 
    ? sorted[midpoint] 
    : (sorted[midpoint - 1] + sorted[midpoint]) / 2
}
```

**Comment by Chalarangelo** [comment]
Hey @atomiks, good ideas! 

* First off, the `deepFlatten` bug has been fixed. My hasty copy-pasting was the cause for this, whoops!
* `last` and `head` of list should be updated to use `slice()` instead of indices, I have that in mind (PRs welcome).
* The `randomIntegerInRange` is perfectly ok by me, PR it and it should be good to go. Add a short explanation, like the one in `randomNumberInRange` and a test case and it should be fine.
* The medial one should probably be shortened somehow, but my brain has mostly shut down right now after so many hours working on these snippets. I'll check it out in the morning, you can PR it if you like though and I'll review it.

Remember to submit the changes to individual files, not the main README file. Thanks a lot for the contributions!

**Comment by atomiks** [comment]
PRs submitted
