### ISSUE TITLE
getURLParameters('https://github.com/Chalarangelo/30-seconds-of-code/issues/new')

### ISSUE THREAD

**Issue by githubmann** [Chalarangelo/30-seconds-of-code#560]
will throw Error "Cannot read property 'reduce' of null"

**Comment by githubmann** [comment]
```js
// will be right
const getURLParameters = url =>
  (url.match(/([^?=&]+)(=([^&]*))/g) || [])
    .reduce((a, v) => ((a[v.slice(0, v.indexOf('='))] = v.slice(v.indexOf('=') + 1)), a), {});
```

**Comment by Chalarangelo** [comment]
Technically the url provided has no parameters, therefore the method will throw an error. It's up to the developer to handle that error, based on the fact that we are not handling errors due to bad input. That being said, this specific method might actually be an exception, as it should theoretically return `null`, `undefined` or and empty object/array. I'm marking this as `opinions needed` so that we can decide on what the best behavior would be in this case. Thanks for reporting this!

**Comment by NielsLeenheer** [comment]
I would definitely not throw an error. Instead I would just return an empty object as the most common thing to do next is checking if a certain parameter exists. 

```
let params = getURLParameters(location.href);
if (params.data) {
   ...
}
```

vs. 

```
let params = getURLParameters(location.href);
if (params) {
   if (params.data) {
      ...
   }
}
```

vs.

```

try {
   let params = getURLParameters(location.href);
   if (param.data) {
      ...
   }
} catch(e) {
}
```

**Comment by skatcat31** [comment]
I'm of the opinion that an empty return Object is a perfectly valid URL parameters return since it is a set of size 0 or more, and a set of 0 is perfectly valid.
```js
// assuming we adhere to URLSearchParams prior art of storage
getURLParameters('google.com') // {}
getURLParameters('google.com?v=value&v=value2&y=value3')
// {"v":["value", "value2"], "y": ["value3"]}
```

Of course now that's assuming that people don't know about [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) and [searchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), but since those are not fully supported yet and it's a living standard, we should keep the snippet

**Comment by Chalarangelo** [comment]
I suppose returning an empty object would be more desirable. 

@skatcat31 Adding `get`, `getAll` and `has` is not necessary, as it's easy enough to use the returned object afterwards to determine these things without the use of custom methods.
