### ISSUE TITLE
why mapObject function use closure

### ISSUE THREAD

**Issue by OPY-bbt** [Chalarangelo/30-seconds-of-code#593]
```js
const mapObject = (arr, fn) => arr.reduce((acc, val) => ((acc[val] = fn(val)), acc), {});
```
This way is more simple and easy to understand

**Comment by skatcat31** [comment]
Yes it's archaic(and I even noted so when I suggested it), however it shows interior deceleration of a closure in design principle for dynamic variable deceleration without declaring a scope block, and without using keywords, instead relying on the comma operator and the implicit declaration.

Granted mapObject is also the same as the following currently, which without composition is a pretty nifty achievement
```js
const mapObject = (arr,fn) => zipObject([arr, arr.map(fn)])
```

**Comment by skatcat31** [comment]
IIRC we did also offer up the reduce version as well...

**Comment by kingdavidmartins** [comment]
@OPY-bbt Good question. Although it might seem simple there is def more going on that meets the eye. As @skatcat31 stated with regards to IIFE, closures, hoisting, and much more other JavaScript specific "side effect" or what have you. Which def provides an amazing learning opportunities for all kinds of dev. Seasoned or not. Especially since JavaScript has it's own quirks  

For example as you can see your proposed snippet breaks with other simple operations.

##### *Our Current Snippet*
```js
mapObject([1, 2, 3, 4], (a, b) => a - b) // { 1: 1, 2: 1, 3: 1, 4: 1 }
mapObject([1, 2, 3, 4], (a, b) => b - a) // { 1: -1, 2: -1, 3: -1, 4: -1 }
```
##### *Your Proposed Snippet* 
```js
mapObject([1, 2, 3, 4], (a, b) => a - b) // { 1: NaN, 2: NaN, 3: NaN, 4: NaN }
mapObject([1, 2, 3, 4], (a, b) => b - a) // { 1: NaN, 2: NaN, 3: NaN, 4: NaN }
```

That being said I def believe it is possible to refactor said snippet in a way that wouldn't hinder functionality and also improve readability. 

If you want @OPY-bbt You can try refactor said snippet and submit a PR. However beware of all the potential edge cases and uses cases.

@Chalarangelo I also think it wouldn't hurt to add the `advance` tag.

**Comment by skatcat31** [comment]
HA! We forgot the advanced tag! Shows where I concentrate my efforts( code quality and stability ). Good catch @kingdavidmartins we should add that tag

**Comment by Chalarangelo** [comment]
I think the original question has been answered and #595 has addressed the tagging issue, so I'm closing this.

**Comment by OPY-bbt** [comment]
Thank you for explaining so much to me. I know there must be a reason for this, but I didn't think of it. Thanks to this project, I learned a lot.However, i think a function does one thing only. like the introduce says 'Maps the values of an array to an object using a function'.

**Comment by skatcat31** [comment]
@OPY-bbt your version was missing something:
```js
const mapObject = (arr, fn) => arr.reduce((acc, val, i, a) => ((acc[val] = fn(val, i, a)), acc), {});
```
```js
mapObject([1, 2, 3, 4], (a, b) => a - b) // { 1: 1, 2: 1, 3: 1, 4: 1 }
mapObject([1, 2, 3, 4], (a, b) => b - a) // { 1: -1, 2: -1, 3: -1, 4: -1 }
```
They are now consistent as it provides the same footprint as map( `(value, index, array)`). While we could switch to that version(less looping), we don't have any examples that show an inline anonymous closure. If I could find a more "useful" example of that I might be more inclined to switch the closure to that snippet, but it's a task that doesn't make much sense due to the fact it makes most code unreadable, while in this snippet it at leas tells us that there is a division of steps.

**Comment by OPY-bbt** [comment]
ok, I agree with the fn need provides the same footprint  as map. Thank you.
