### ISSUE TITLE
[FEATURE] Refactor `flatten`

### ISSUE THREAD

**Issue by tangweikun** [Chalarangelo/30-seconds-of-code#622]
## [FEATURE] Refactor `flatten`
**Category:** Array
### Possible Solution
```js
const flatten = (arr, depth = 1) =>
  arr.reduce(
    (a, v) =>
      a.concat(depth > 1 && Array.isArray(v) ? flatten(v, depth - 1) : v),
    [],
  )
```

**Comment by Chalarangelo** [comment]
I think this might break for a few cases, let me test this more in-depth tomorrow and see if there's anything missing. @skatcat31 care to check this one out? I might be missing something here either way!

**Comment by skatcat31** [comment]
That should work just fine since it's combining the two conditions into a single one. The depth must be greater than 1(checked in current flatten) AND the value is an array is equal to our current functionality and has the added benefit of being safe against negative values and 0(which in current cause deepFlatten)

Ours has a problem in that if it is not exactly equal to 1 AND positive, it becomes deep flatten.

Flatten prior arts are usually fully deep, ours allows the option of a differing depth but has incorrect conditionals.

Some testing would be nice, but this is as simple as

`if (case1) if(case2)` being the same as `if (case1 && case2)`

**Comment by skatcat31** [comment]
We should probably decide on if we want to keep it `depth !== 1` and document the deep functionality by providing 0 as a depth and watching it fully flatten a nested array.

**Comment by Chalarangelo** [comment]
I don't think we want it to default to deep flattening, we already  have a `deepFlatten` snippet for that. If the changes suggested above work properly, please PR them asap and check if all tests work.
