### ISSUE TITLE
[question] About curry

### ISSUE THREAD

**Issue by Shenmin-Z** [Chalarangelo/30-seconds-of-code#627]
In the description of `curry` function, it says `use recursion`. My understanding of recursion is a function that CALLs itself. Here the `curry` function only returns itself with some binding, not calling itself. So I feel it's not recursion.

**Comment by elderhsouza** [comment]
I think you're right. It's possible that the description isn't matching with the actual implementation, it had a couple prior versions and if I remember it correctly, it used recursion before.

**Comment by skatcat31** [comment]
Recursion in the `Strong Typed Classical Inheritance`(often called OOP, like C++, Java, etc.) is defined as
>a function that calls itself

While recursion is defined generally as
> the repeated application of a recursive procedure or definition.

Recursive in the CS world means
> relating to or involving a program or routine of which a part requires the application of the whole, so that its explicit interpretation requires in general many successive executions.

So yes, `curry` is recursive. It MUST reference and execute `curry`(recursive) to be able to be executed(recursion).

So in general CS with regards to OOP and all patterns of `Strong/Dynamic Typed Classical/Prototype Inheritance/Reference` languages(ES6 is of the `Dynamically Typed Prototype Reference` family), recursion is defined as
> A function that requires reference to itself

After all `curry` requires itself to reach arity before execution, otherwise it references itself and curries itself to a new recursive execution context, which is impossible to do without `curry`.

**Comment by Chalarangelo** [comment]
Sorry for being late to the party. When a snippet says `Uses recursion` there is a very specific reason for having that thing mentioned in the description - **snippets that call the defined function by name need to have this comment, so that developers know that they need to remember to rename any references inside the snippet itself if the function is renamed.** Therefore this part of the description is very important and should not be altered (in fact there might even be snippets that do not have this comment in the description, while they should). I'm closing the issue on that basis.
